# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        command: 'php artisan serve --host=0.0.0.0'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - 8000:8000
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
networks:
    sail:
        driver: bridge
